export const selectors = {
  navLoginLink: 'nav-login-link',
  demoLoginUser001: 'demo-login-user-001',
  loginSubmitButton: 'login-submit-button',
  searchInput: 'search-input',
  searchButton: 'search-button',
  addToCartProd001: 'add-to-cart-prod-001',
  addToCartProd002: 'add-to-cart-prod-002',
  addToCartProd003: 'add-to-cart-prod-003',
  cartLink: 'cart-link',
  cartQtyIncreaseProd001: 'cart-qty-increase-prod-001',
  cartQtyDecreaseProd001: 'cart-qty-decrease-prod-001',
  checkoutButton: 'checkout-button',
  continueToPaymentButton: 'continue-to-payment-button',
  paymentCardName: 'payment-card-name',
  paymentCardNumber: 'payment-card-number',
  paymentExpiry: 'payment-expiry',
  paymentCvv: 'payment-cvv',
  placeOrderButton: 'place-order-button',
  orderNumber: 'order-number',
  orderTotals: 'order-totals',
  continueShoppingAfterOrder: 'continue-shopping-after-order',
};
