name: API Automation Tests

on:
  push:
    branches:
      - Kavya_FinalAssesment

  pull_request:
    branches:
      - Kavya_FinalAssesment

jobs:
  api-tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apitesting

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version

      - name: Run API Tests
        run: mvn clean test

        env:
          KAVYA_DEMOQA_BASE_URL: ${{ secrets.KAVYA_DEMOQA_BASE_URL }}
          KAVYA_DEMOQA_USERNAME_PREFIX: ${{ secrets.KAVYA_DEMOQA_USERNAME_PREFIX }}
          KAVYA_DEMOQA_USERNAME: ${{ secrets.KAVYA_DEMOQA_USERNAME }}
          KAVYA_DEMOQA_PASSWORD: ${{ secrets.KAVYA_DEMOQA_PASSWORD }}

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: apitesting/target/surefire-reports

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: apitesting/target/site/allure-maven-plugin